export enum ACTION_TYPES {}
export enum URLS {
   BASE_URL = 'https://api.github.com',
}
export enum ACTION_TYPES {
   FETCH_REPOS = 'FETCH_REPOS',
   FETCH_REPOS_START = 'FETCH_REPOS_START',
   FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS',
   FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE',
   ADD_TO_HISTORY = 'ADD_TO_HISTORY',
}
